package constant

const (
	Slash                       = "/"
	RouterDefinition            = "/Router/"
	RouterPrefixString          = "Router-%s/"
	ServiceDefinition           = "/Service/"
	ServicePrefixString         = "Service-%s/"
	NodeDefinition              = "/Node/"
	NodePrefixString            = "Node-%s/"
	NodePrefixDefinition        = "/Node/Node-"
	HealthCheckPrefixDefinition = "/HealthCheck/HC-"
	HealthCheckPrefixString     = "HC-%s/"

	IdKeyString          = "ID"
	NameKeyString        = "Name"
	ServiceKeyString     = "Service"
	HostKeyString        = "Host"
	PortKeyString        = "Port"
	StatusKeyString      = "Status"
	HealthCheckKeyString = "HealthCheck"
	FrontendApiKeyString = "FrontendApi"
	BackendApiKeyString  = "BackendApi"
	PathKeyString        = "Path"
	TimeoutKeyString     = "Timeout"
	IntervalKeyString    = "Interval"
	RetryKeyString       = "Retry"
	RetryTimeKeyString   = "RetryTime"
	NodeKeyString        = "Node"
	FailedTimesKeyString = "FailedTimes"
)
